### ISSUE TITLE
Enable use of  MouseKeys.speedLimit = 50;

### ISSUE THREAD

**Issue by michabu** [keyboardio/Kaleidoscope-MouseKeys#20]
In order to quickly and precisely be able to reach a certain point on the screen I imagine it would be good to quickly accelerate to a still handleable speed by holding buttons down. Close to the desired destination I would only short-press the keys to maneuver it to the final destination.

At the moment the mouse-pointer accelerates to a speed that is to fast for me to still follow, so it would be nice to be able to set the maximum speed, it is accelerated to, in the API.

**Comment by algernon** [comment]
As an interim solution, you can set `MouseWrapper.speedLimit = 50;` (after including `MouseWrapper.h`). That should have the desired effect.

We could expose the same setting via `MouseKeys`, like `MouseKeys.speedLimit(50)` or something along those lines.

**Comment by algernon** [comment]
I believe #26 addresses this, so closing it now. Please feel free to reopen if the provided APIs aren't enough.
