### ISSUE TITLE
Overlay for visual guidance when mouse warping

### ISSUE THREAD

**Issue by unode** [keyboardio/Kaleidoscope-MouseKeys#30]
Hi everyone,

This might be a little out of scope but I'd like to hear your thoughts on this.
I'm quite fond of the mouse warping controls, however I find it hard to predict where the mouse is going to end up without some kind of visual guidance or a reasonable amount of trial-and-error.

Searching on Google I have not yet found any tool that could provide the kind of visual feedback described next. If you are aware of any such tool I'd be interested in giving a try.

Below is a mock-up of what I have in mind for a graphical overlay to be displayed on the user's screen when using the Mouse warping keys.
This would probably have to live as a third-party tool with multi-platform support.

### How to interpret
The quadrants (red) are shown for a few seconds when pressing `Key_mouseWarpEnd`.
Pressing `Key_mouseWarpNW` then warps the mouse and displays the next layer (green), and continues with alternating colors until the target is reached.
Alternatively a single color is used and the previous quadrant is hidden from display.

#### Multi-color persistent quadrants
So for instance warping to the submit button on this issue would result in the following.

After `Key_mouseWarpEnd`:
![1](https://user-images.githubusercontent.com/122319/44957268-b6511d80-aed0-11e8-9779-8d07703f0fa6.png)

After `Key_mouseWarpSE`:
![2](https://user-images.githubusercontent.com/122319/44957272-b9e4a480-aed0-11e8-855b-e4165428799d.png)

After `Key_mouseWarpNW`:
![3](https://user-images.githubusercontent.com/122319/44957275-bbae6800-aed0-11e8-8c3b-3f93c63845da.png)

After `Key_mouseWarpSW`:
![4](https://user-images.githubusercontent.com/122319/44957277-be10c200-aed0-11e8-87bd-ac5515924d44.png)

At what point hitting `Key_mouseWarpSE` will get us on or very close to the target and hitting one of the `North` directions will get us exactly on target.

#### Single(or pair)-color active quadrants only
An alternative navigation could use a single or a pair of colors and stop displaying the previous quadrant division:
![1](https://user-images.githubusercontent.com/122319/44957404-6f642780-aed2-11e8-8137-3a61ab29171d.png)
![2a](https://user-images.githubusercontent.com/122319/44957406-70955480-aed2-11e8-8533-1e7223c163d1.png)
![3a](https://user-images.githubusercontent.com/122319/44957408-72f7ae80-aed2-11e8-9e47-2a9ff1b15cd5.png)
![4a](https://user-images.githubusercontent.com/122319/44957414-902c7d00-aed2-11e8-91a1-616df3960ea0.png)

**Comment by obra** [comment]
That'd be a very cool thing, but I believe it'd require a host-side driver
-- there's nothing we could easily do from the keyboard to generate it. I'd
played with having the mouse trace the next quadrants when you zoom in, but
I recall it being pretty slow.
ᐧ

**Comment by unode** [comment]
Hi Jesse,

Thanks for reply (and the awesome keyboard).

I suspected it would be quite-hard/impossible to do without any kind of assistance from the host or else it would probably be part of the current code :grinning: .

With regards to tracing and it being slow, were your tests sending full mouse movement or corner coordinates only?

I was thinking of having some kind of OSD software handle the drawing given a set of coordinates.
https://askubuntu.com/questions/328543/drawing-over-the-desktop mentions a few possibilities as well as performance issues with non-composed desktops.
https://github.com/atheme-legacy/libaosd showed up later and seems lighter and flexible enough for this use-case.

Given the keyboard already does all the math (with caveats on non-symmetric multi-display setups)... would the communication be something fitting the Focus plugin or can you think of better ways to implement something like this?
If you also tried this direction, was the communication the bottleneck in terms of speed?

**Comment by obra** [comment]
Focus could...probably be a reasonable way to hook that together?

It might make sense to try having warping jump to the four possible "next
steps" before jumping to the current point. That could at least be done all
in the keyboard.

Best,
Jesse
ᐧ

**Comment by algernon** [comment]
> Focus could...probably be a reasonable way to hook that together?

Yep, can do that.

> It might make sense to try having warping jump to the four possible "next
steps" before jumping to the current point. That could at least be done all
in the keyboard.

I think this would be mighty annoying. If done too fast, one won't be able to follow. If done too slow, then the delay becomes an issue. Besides... when would you jump the cursor around? When pressing a warp key, the user already selected a quadrant... for the jumping to be of any use, we'd need a "start warp" key.

Now, having such a key, with the possibility to override the functionality of it... that would be useful. The jumping around could be one example of what it can be used for.

**Comment by unode** [comment]
> we'd need a "start warp" key.

Isn't this achievable with `Key_mouseWarpEnd` ?
My plan is/was to use this key as a trigger to the quadrant painting on-screen and lighting up the warp keys's LEDs in accordance to the quadrant colors used.

**Comment by algernon** [comment]
I guess `Key_mouseWarpEnd` could be re-used for this purpose, yeah.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#372.
