### ISSUE TITLE
more precise acceleration controls

### ISSUE THREAD

**Issue by ToyKeeper** [keyboardio/Kaleidoscope-MouseKeys#7]
The mouse cursor acceleration seems to easily get out of hand, going rapidly from slow movement to extremely fast movement...  even with the accelSpeed set to 1.

It would be nice if this value (and mouse speed in general) could be a float instead, to make it accelerate in smaller increments.  On this hardware that might perhaps mean using fixed-point, since the hardware has no native floating-point and the emulation libraries for that are a big thing to pull in for just one change.

Another way to manage the acceleration might be to give it a maximum speed value.

I might mess with this to see if I can make it feel a bit better.  At minimum, I'd like to make it easier to not zip my cursor offscreen entirely (using x2x), and easier to move the cursor precisely enough to click links.

**Comment by algernon** [comment]
You can fiddle with `MouseKeys.speedDelay` and `MouseKeys.accelDelay` which control how fast speed and acceleration are applied. You can control the accel speed a bit better this way.

There is also the [Kaleidoscope-MouseGears](https://github.com/keyboardio/Kaleidoscope-MouseGears) plugin that has a preset list of speed & delay pairs between which you can switch.

**Comment by obra** [comment]
ToyKeeper:

I agree 100% on the problem statement. And, in fact, nousing felt better
when we used floating point math for it. The problem is that even simple
floating point math adds significant and unacceptable bloat to the code 
size when we're working on an embedded device like the AVR. If we can
fix it without going down that route, it'd be amazing

**Comment by ToyKeeper** [comment]
I'll take a look at it when I get a chance.  Floating-point may be way too big here, but fixed-point is small and easy.

**Comment by ToyKeeper** [comment]
Fixed it.  The mouse keys should be much smoother now.
